# Generated by Django 4.1 on 2022-08-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='destaque',
            name='nome',
            field=models.CharField(default='Produto em destaque', max_length=150, verbose_name='Nome de destaque:'),
            preserve_default=False,
        ),
    ]
