# Generated by Django 4.1 on 2022-08-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_destaque_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='Produto produzido em Serrinha dos Pintos, ótima qualidade, fresquinhos!!', verbose_name='Descrição do produto:'),
            preserve_default=False,
        ),
    ]
