# Generated by Django 4.1 on 2022-08-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_produto_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destaque',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='destaque',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.destaque'),
            preserve_default=False,
        ),
    ]
