# Generated by Django 4.1 on 2022-08-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_destaque_produto_produto_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='destaque',
        ),
        migrations.DeleteModel(
            name='Destaque',
        ),
    ]
